// src/app/inicio/inicio.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-inicio',
  standalone: true,
  imports: [],
  templateUrl: './inicio.component.html',
  styleUrl: './inicio.component.css'
})
export class InicioComponent {

  constructor() {
  }

}









<div>
    <h1>Bienvenidos</h1>
    <a href="">
        <img class="img" src="imgs/29-FTD_0512.jpg" alt="">
    </a>
</div>

// src/components/Inicio.jsx
import "../assets/css/App.css";

export const Inicio = () => {
  return (
    <div className="inicio-container">
      <section className="inicio-section">
        <div className="inicio-title">
          <h1>Dogtoralia</h1>
        </div>
        <div className="inicio-img-container">
          <img
            className="inicio-img"
            src="public/imgs/Bienvenida.jpg"
            alt="Bienvenida"
          />
        </div>
      </section>
    </div>
  );
};
